# Generated by Django 6.1.1 on 2026-09-30 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准')], default='draft', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ecr_no', models.CharField(blank=True, max_length=64)),
                ('eco_no', models.CharField(blank=True, max_length=64)),
                ('affected_products', models.TextField(blank=True)),
                ('affected_region', models.CharField(blank=True, max_length=255)),
                ('initiating_factory', models.CharField(blank=True, max_length=255)),
                ('affected_factories', models.TextField(blank=True)),
                ('ccb_owner', models.CharField(blank=True, max_length=255)),
                ('change_owner', models.CharField(blank=True, max_length=255)),
                ('planned_eco_date', models.DateField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_request',
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'approved'])), name='change_request_valid_status')],
            },
        ),
    ]
