# Generated by Django 6.1.1 on 2026-09-30 15:05

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def check_duplicate_numbers(apps, schema_editor):
    records = apps.get_model('changes', 'ChangeRequest').objects.using(schema_editor.connection.alias)
    conflicts = []
    for field in ('ecr_no', 'eco_no'):
        duplicates = records.exclude(**{field: ''}).values(field).annotate(total=Count('pk')).filter(total__gt=1).order_by(field)
        for duplicate in duplicates:
            ids = list(records.filter(**{field: duplicate[field]}).order_by('pk').values_list('pk', flat=True))
            conflicts.append(f"{field}={duplicate[field]!r}, application IDs={ids}")
    if conflicts:
        raise RuntimeError('Duplicate non-empty numbers; confirm corrections before migrating. No records were changed.\n' + '\n'.join(conflicts))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('changes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_duplicate_numbers, migrations.RunPython.noop),
        migrations.AddField(
            model_name='changerequest',
            name='eco_no_unique',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.NullIf(models.F('eco_no'), models.Value('')), output_field=models.CharField(max_length=64)),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='ecr_no_unique',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.NullIf(models.F('ecr_no'), models.Value('')), output_field=models.CharField(max_length=64)),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.UniqueConstraint(fields=('ecr_no_unique',), name='change_request_ecr_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.UniqueConstraint(fields=('eco_no_unique',), name='change_request_eco_no_unique'),
        ),
    ]
