# Generated by Django 6.1.1 on 2026-10-01 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_unique_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revision', '升版'), ('addition', '新增'), ('discontinuation', '停用')], max_length=20)),
                ('material_no', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_class', models.CharField(blank=True, max_length=255)),
                ('spare_part', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('optional_part', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('old_revision', models.CharField(blank=True, max_length=255)),
                ('new_revision', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(blank=True, max_length=255)),
                ('detailed_class', models.CharField(blank=True, max_length=255)),
                ('discontinued_project', models.CharField(blank=True, max_length=255)),
                ('change_description', models.TextField(blank=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='changes.changerequest')),
            ],
            options={
                'db_table': 'material_change',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['revision', 'addition', 'discontinuation'])), name='material_valid_category'), models.CheckConstraint(condition=models.Q(('spare_part__in', ['', 'Y', 'N'])), name='material_valid_spare_part'), models.CheckConstraint(condition=models.Q(('optional_part__in', ['', 'Y', 'N'])), name='material_valid_optional_part')],
            },
        ),
    ]
