# Generated by Django 6.1.1 on 2026-10-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_materialchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialchange',
            name='request_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='materialchange',
            constraint=models.UniqueConstraint(fields=('change', 'request_id'), name='material_unique_request'),
        ),
    ]
