# Generated by Django 6.1.1 on 2026-10-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_materialchange_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_group', models.CharField(max_length=16)),
                ('location_item', models.CharField(max_length=32)),
                ('disposition', models.CharField(blank=True, choices=[('', ''), ('Use-up', 'Use-up'), ('Scrap', 'Scrap'), ('Rework', 'Rework'), ('No Change', 'No Change'), ('Balance', 'Balance'), ('NA', 'NA')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='changes.materialchange')),
            ],
            options={
                'db_table': 'material_disposition',
                'ordering': ['location_item'],
                'constraints': [models.UniqueConstraint(fields=('material', 'location_item'), name='disposition_unique_location'), models.CheckConstraint(condition=models.Q(('disposition__in', ['', 'Use-up', 'Scrap', 'Rework', 'No Change', 'Balance', 'NA'])), name='disposition_valid_value'), models.CheckConstraint(condition=models.Q(models.Q(('location_group', 'company'), ('location_item__in', ['company_finished', 'company_wip', 'company_raw'])), models.Q(('location_group', 'supplier'), ('location_item__in', ['supplier_finished', 'supplier_wip', 'supplier_raw', 'supplier_rma'])), models.Q(('location_group', 'customer'), ('location_item__in', ['customer_return', 'customer_site', 'customer_spares'])), _connector='OR'), name='disposition_valid_location')],
            },
        ),
    ]
