# Generated by Django 6.1.1 on 2026-10-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_materialdisposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=1)),
                ('remark', models.TextField(blank=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='changes.changerequest')),
            ],
            options={
                'db_table': 'question_response',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('change', 'number'), name='question_unique_number'), models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 27)), name='question_valid_number'), models.CheckConstraint(condition=models.Q(('answer__in', ['', 'Y', 'N'])), name='question_valid_answer')],
            },
        ),
    ]
