# Generated by Django 6.1.1 on 2026-10-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0006_questionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcrActionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=7)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('completed', '完成'), ('not_applicable', '不适用')], max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecr_responses', to='changes.changerequest')),
            ],
            options={
                'db_table': 'ecr_action_response',
                'constraints': [models.UniqueConstraint(fields=('change', 'action_key'), name='ecr_unique_action'), models.CheckConstraint(condition=models.Q(('action_key__in', ['ecr_001', 'ecr_002', 'ecr_003', 'ecr_004', 'ecr_005', 'ecr_006', 'ecr_007', 'ecr_008', 'ecr_009', 'ecr_010', 'ecr_011', 'ecr_012', 'ecr_013', 'ecr_014', 'ecr_015', 'ecr_016', 'ecr_017', 'ecr_018', 'ecr_019', 'ecr_020', 'ecr_021', 'ecr_022', 'ecr_023', 'ecr_024', 'ecr_025', 'ecr_026', 'ecr_027', 'ecr_028', 'ecr_029', 'ecr_030', 'ecr_031', 'ecr_032', 'ecr_033', 'ecr_034', 'ecr_035', 'ecr_036', 'ecr_037', 'ecr_038', 'ecr_039', 'ecr_040', 'ecr_041', 'ecr_042', 'ecr_043', 'ecr_044', 'ecr_045', 'ecr_046', 'ecr_047', 'ecr_048', 'ecr_049', 'ecr_050', 'ecr_051', 'ecr_052', 'ecr_053', 'ecr_054', 'ecr_055', 'ecr_056', 'ecr_057', 'ecr_058', 'ecr_059', 'ecr_060', 'ecr_061'])), name='ecr_valid_action'), models.CheckConstraint(condition=models.Q(('status__in', ['', 'completed', 'not_applicable'])), name='ecr_valid_status')],
            },
        ),
    ]
