# Generated by Django 6.1.1 on 2026-10-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0007_ecractionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoActionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=7)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('completed', '完成'), ('not_applicable', '不适用'), ('implementation_stage', '在实施阶段完成')], max_length=24)),
                ('date', models.DateField(blank=True, null=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_responses', to='changes.changerequest')),
            ],
            options={
                'db_table': 'eco_action_response',
                'constraints': [models.UniqueConstraint(fields=('change', 'action_key'), name='eco_unique_action'), models.CheckConstraint(condition=models.Q(('action_key__in', ['eco_001', 'eco_002', 'eco_003', 'eco_004', 'eco_005', 'eco_006', 'eco_007', 'eco_008', 'eco_009', 'eco_010', 'eco_011', 'eco_012', 'eco_013', 'eco_014', 'eco_015', 'eco_016', 'eco_017', 'eco_018', 'eco_019', 'eco_020', 'eco_021', 'eco_022', 'eco_023', 'eco_024', 'eco_025', 'eco_026', 'eco_027', 'eco_028', 'eco_029', 'eco_030', 'eco_031', 'eco_032', 'eco_033', 'eco_034', 'eco_035', 'eco_036', 'eco_037', 'eco_038', 'eco_039', 'eco_040', 'eco_041', 'eco_042', 'eco_043', 'eco_044', 'eco_045', 'eco_046', 'eco_047', 'eco_048', 'eco_049', 'eco_050', 'eco_051', 'eco_052', 'eco_053', 'eco_054', 'eco_055', 'eco_056', 'eco_057', 'eco_058', 'eco_059', 'eco_060', 'eco_061'])), name='eco_valid_action'), models.CheckConstraint(condition=models.Q(('status__in', ['', 'completed', 'not_applicable', 'implementation_stage'])), name='eco_valid_status')],
            },
        ),
    ]
