# Generated by Django 6.1.1 on 2026-10-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0008_ecoactionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmcReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('introduction', models.TextField(blank=True)),
                ('legend', models.TextField(blank=True)),
                ('definitions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emc_reference', to='changes.changerequest')),
            ],
            options={
                'db_table': 'emc_reference',
            },
        ),
        migrations.CreateModel(
            name='EmcReferenceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_collation='utf8mb4_bin', max_length=64)),
                ('label', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='changes.emcreference')),
            ],
            options={
                'db_table': 'emc_reference_row',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmcReferenceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_collation='utf8mb4_bin', max_length=64)),
                ('label', models.TextField(blank=True)),
                ('group_label', models.CharField(blank=True, max_length=255)),
                ('standard_reference', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='changes.emcreference')),
            ],
            options={
                'db_table': 'emc_reference_test',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmcReferenceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, choices=[('X', '需要测试'), ('(X)', '需要分析')], db_collation='utf8mb4_bin', max_length=3)),
                ('remark', models.TextField(blank=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='changes.emcreference')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.emcreferencerow')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.emcreferencetest')),
            ],
            options={
                'db_table': 'emc_reference_cell',
            },
        ),
        migrations.AddConstraint(
            model_name='emcreferencerow',
            constraint=models.UniqueConstraint(fields=('reference', 'key'), name='emc_row_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencerow',
            constraint=models.UniqueConstraint(fields=('reference', 'id'), name='emc_row_owner'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencerow',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gt', 0)), name='emc_row_valid_order'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencetest',
            constraint=models.UniqueConstraint(fields=('reference', 'key'), name='emc_test_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencetest',
            constraint=models.UniqueConstraint(fields=('reference', 'id'), name='emc_test_owner'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencetest',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gt', 0)), name='emc_test_valid_order'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencecell',
            constraint=models.UniqueConstraint(fields=('row', 'test'), name='emc_unique_cell'),
        ),
        migrations.AddConstraint(
            model_name='emcreferencecell',
            constraint=models.CheckConstraint(condition=models.Q(('mark__in', ['', 'X', '(X)'])), name='emc_valid_mark'),
        ),
    ]

    # Enforce row/test ownership even for writes outside the API.
    operations += [
        migrations.RunSQL(
            "ALTER TABLE emc_reference_cell ADD CONSTRAINT emc_cell_row_owner_fk "
            "FOREIGN KEY (reference_id, row_id) REFERENCES emc_reference_row (reference_id, id) ON DELETE CASCADE",
            "ALTER TABLE emc_reference_cell DROP FOREIGN KEY emc_cell_row_owner_fk",
        ),
        migrations.RunSQL(
            "ALTER TABLE emc_reference_cell ADD CONSTRAINT emc_cell_test_owner_fk "
            "FOREIGN KEY (reference_id, test_id) REFERENCES emc_reference_test (reference_id, id) ON DELETE CASCADE",
            "ALTER TABLE emc_reference_cell DROP FOREIGN KEY emc_cell_test_owner_fk",
        ),
    ]
