# Generated by Django 6.1.1 on 2026-10-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0009_emc_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPlanResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(db_collation='utf8mb4_bin', max_length=8)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_plan_responses', to='changes.changerequest')),
            ],
            options={
                'db_table': 'execution_plan_response',
                'constraints': [models.UniqueConstraint(fields=('change', 'activity_key'), name='plan_unique_activity'), models.CheckConstraint(condition=models.Q(('activity_key__in', ['plan_001', 'plan_002', 'plan_003', 'plan_004', 'plan_005', 'plan_006', 'plan_007', 'plan_008', 'plan_009', 'plan_010', 'plan_011'])), name='plan_valid_activity'), models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='plan_date_order')],
            },
        ),
    ]
