# Generated by Django 6.1.1 on 2026-10-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0010_executionplanresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_assessment', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=24)),
                ('final_conclusion', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=16)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='significant_assessment', to='changes.changerequest')),
            ],
            options={
                'db_table': 'significant_assessment',
                'constraints': [models.CheckConstraint(condition=models.Q(('f_assessment__in', ['', 'not_applicable', 'ra_non_significant', 'ra_significant'])), name='sig_valid_f'), models.CheckConstraint(condition=models.Q(('final_conclusion__in', ['', 'significant', 'non_significant'])), name='sig_valid_final')],
            },
        ),
        migrations.CreateModel(
            name='SignificantChartResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_key', models.CharField(db_collation='utf8mb4_bin', max_length=1)),
                ('applicability', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=1)),
                ('reason', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=16)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significant_charts', to='changes.changerequest')),
            ],
            options={
                'db_table': 'significant_chart_response',
                'constraints': [models.UniqueConstraint(fields=('change', 'chart_key'), name='sig_unique_chart'), models.CheckConstraint(condition=models.Q(('chart_key__in', ['0', 'A', 'B', 'C', 'D', 'E'])), name='sig_valid_chart'), models.CheckConstraint(condition=models.Q(('applicability__in', ['', 'Y', 'N'])), name='sig_valid_applicability'), models.CheckConstraint(condition=models.Q(('result__in', ['', 'not_applicable', 'significant', 'continue', 'non_significant'])), name='sig_valid_result'), models.CheckConstraint(condition=models.Q(models.Q(('chart_key', '0'), ('result', '')), models.Q(('chart_key__in', ['A', 'B', 'C', 'D']), ('result__in', ['', 'not_applicable', 'significant', 'continue'])), models.Q(('chart_key', 'E'), ('result__in', ['', 'not_applicable', 'significant', 'non_significant'])), _connector='OR'), name='sig_result_for_chart')],
            },
        ),
        migrations.CreateModel(
            name='SignificantQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(db_collation='utf8mb4_bin', max_length=16)),
                ('answer', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=1)),
                ('reason', models.TextField(blank=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significant_questions', to='changes.changerequest')),
            ],
            options={
                'db_table': 'significant_question_response',
                'constraints': [models.UniqueConstraint(fields=('change', 'question_key'), name='sig_unique_question'), models.CheckConstraint(condition=models.Q(('question_key__in', ['sub_a_1', 'sub_a_2', 'sub_a_3', 'sub_a_4', 'sub_b_1', 'sub_b_1_1', 'sub_b_1_2', 'sub_b_1_3', 'sub_b_2', 'sub_b_2_1', 'sub_b_3', 'sub_b_3_1', 'sub_b_4', 'sub_b_4_1', 'sub_c_1', 'sub_c_2', 'sub_c_3', 'sub_c_4', 'sub_c_5', 'sub_c_6', 'sub_c_7', 'sub_c_8', 'sub_d_1', 'sub_d_2', 'sub_d_3', 'sub_d_4', 'sub_d_5', 'sub_d_5_1', 'sub_e_1', 'sub_e_2', 'sub_e_3', 'sub_e_4', 'sub_e_5', 'sub_e_6', 'sub_e_7', 'sub_e_8', 'sub_e_8_1'])), name='sig_valid_question'), models.CheckConstraint(condition=models.Q(('answer__in', ['', 'Y', 'N'])), name='sig_valid_answer')],
            },
        ),
    ]
