# Generated by Django 6.1.1 on 2026-10-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_reviewer_group(apps, schema_editor):
    apps.get_model('auth', 'Group').objects.using(schema_editor.connection.alias).get_or_create(name='审核员')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('changes', '0011_significant_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_reviewer_group, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review_record',
            },
        ),
        migrations.AddField(
            model_name='changerequest',
            name='review_mode',
            field=models.CharField(blank=True, choices=[('designated', '指定审核'), ('public', '公开审核')], db_collation='utf8mb4_bin', max_length=16),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.CheckConstraint(condition=models.Q(('review_mode__in', ['', 'designated', 'public'])), name='change_valid_review_mode'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='changes.changerequest'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reviewrecord',
            constraint=models.UniqueConstraint(fields=('change', 'reviewer'), name='review_unique_person'),
        ),
    ]
