# Generated by Django 6.1.1 on 2026-10-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_submissions(apps, schema_editor):
    Change = apps.get_model('changes', 'ChangeRequest')
    Round = apps.get_model('changes', 'ReviewRound')
    Record = apps.get_model('changes', 'ReviewRecord')
    alias = schema_editor.connection.alias
    for change in Change.objects.using(alias).filter(submitted_at__isnull=False, review_mode__in=['designated', 'public'], status__in=['pending', 'approved']):
        round = Round.objects.using(alias).create(change_id=change.pk, number=1, review_mode=change.review_mode,
            title=change.title, ecr_no=change.ecr_no, eco_no=change.eco_no, submitted_at=change.submitted_at,
            state=change.status, approved_at=change.updated_at if change.status == 'approved' else None)
        Record.objects.using(alias).filter(change_id=change.pk).update(round_id=round.pk)
        Change.objects.using(alias).filter(pk=change.pk).update(current_review_round=1)


def check_reverse(apps, schema_editor):
    alias = schema_editor.connection.alias
    Round = apps.get_model('changes', 'ReviewRound')
    Feedback = apps.get_model('changes', 'ReviewFeedback')
    if Round.objects.using(alias).filter(models.Q(number__gt=1) | models.Q(state='returned')).exists() or Feedback.objects.using(alias).exists():
        raise RuntimeError('已有退回、重提或反馈记录，不能直接回退0013；请先制定数据恢复方案。')


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0012_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_feedback',
            },
        ),
        migrations.CreateModel(
            name='ReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('review_mode', models.CharField(db_collation='utf8mb4_bin', max_length=16)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('ecr_no', models.CharField(max_length=64)),
                ('eco_no', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField()),
                ('state', models.CharField(db_collation='utf8mb4_bin', default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'review_round',
            },
        ),
        migrations.RemoveConstraint(
            model_name='changerequest',
            name='change_request_valid_status',
        ),
        migrations.RemoveConstraint(
            model_name='reviewrecord',
            name='review_unique_person',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='current_review_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('returned', '待修订')], default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'approved', 'returned'])), name='change_request_valid_status'),
        ),
        migrations.AddField(
            model_name='reviewfeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='changes.changerequest'),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfeedback',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='changes.reviewround'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='changes.reviewround'),
        ),
        migrations.AddConstraint(
            model_name='reviewrecord',
            constraint=models.UniqueConstraint(fields=('round', 'reviewer'), name='review_unique_person'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.UniqueConstraint(fields=('change', 'number'), name='review_unique_round'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.UniqueConstraint(fields=('change', 'request_id'), name='review_unique_submission'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='review_round_positive'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.CheckConstraint(condition=models.Q(('review_mode__in', ['designated', 'public'])), name='review_round_mode'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'approved', 'returned'])), name='review_round_state'),
        ),
        migrations.AddConstraint(
            model_name='reviewfeedback',
            constraint=models.UniqueConstraint(fields=('round', 'author', 'request_id'), name='review_unique_feedback'),
        ),
        migrations.RunPython(seed_existing_submissions, check_reverse),
    ]
