# Generated by Django 6.1.1 on 2026-10-05 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prevent_history_loss(apps, schema_editor):
    if apps.get_model('changes', 'ReviewIssue').objects.exists() or apps.get_model('changes', 'ReviewIssueEvent').objects.exists():
        raise RuntimeError('已有正式审核意见或处理记录，不能直接回退0014；须先制定历史保留方案。')


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0013_review_rounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('state', models.CharField(db_collation='utf8mb4_bin', default='awaiting_reply', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='changes.changerequest')),
                ('source_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.reviewround')),
            ],
            options={
                'db_table': 'review_issue',
            },
        ),
        migrations.CreateModel(
            name='ReviewIssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=16)),
                ('version', models.PositiveIntegerField(default=0)),
                ('request_id', models.UUIDField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_events', to='changes.changerequest')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='changes.reviewissue')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.reviewround')),
            ],
            options={
                'db_table': 'review_issue_event',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewissue',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['awaiting_reply', 'awaiting_review', 'resolved'])), name='review_issue_state'),
        ),
        migrations.AddConstraint(
            model_name='reviewissue',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='review_issue_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewissueevent',
            constraint=models.UniqueConstraint(fields=('change', 'author', 'request_id', 'position'), name='review_issue_request'),
        ),
        migrations.RunPython(migrations.RunPython.noop, prevent_history_loss),
    ]
