# Generated by Django 6.1.1 on 2026-10-08 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_admin_group(apps, schema_editor):
    apps.get_model('auth', 'Group').objects.using(schema_editor.connection.alias).get_or_create(name='反馈管理员')


def prevent_history_loss(apps, schema_editor):
    alias = schema_editor.connection.alias
    if apps.get_model('changes', 'SystemFeedback').objects.using(alias).exists():
        raise RuntimeError('已有系统反馈，不能直接回退0015；须先制定历史保留方案。')


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0014_review_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('problem', '问题'), ('suggestion', '建议'), ('other', '其他')], db_collation='utf8mb4_bin', max_length=16)),
                ('content', models.TextField()),
                ('status', models.CharField(db_collation='utf8mb4_bin', default='pending', max_length=16)),
                ('request_id', models.UUIDField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_feedback',
            },
        ),
        migrations.CreateModel(
            name='SystemFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('from_status', models.CharField(db_collation='utf8mb4_bin', max_length=16)),
                ('to_status', models.CharField(db_collation='utf8mb4_bin', max_length=16)),
                ('request_id', models.UUIDField()),
                ('base_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='changes.systemfeedback')),
            ],
            options={
                'db_table': 'system_feedback_event',
            },
        ),
        migrations.AddConstraint(
            model_name='systemfeedback',
            constraint=models.UniqueConstraint(fields=('submitter', 'request_id'), name='sys_feedback_request'),
        ),
        migrations.AddConstraint(
            model_name='systemfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['problem', 'suggestion', 'other'])), name='sys_feedback_category'),
        ),
        migrations.AddConstraint(
            model_name='systemfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'closed'])), name='sys_feedback_status'),
        ),
        migrations.AddConstraint(
            model_name='systemfeedbackevent',
            constraint=models.UniqueConstraint(fields=('feedback', 'request_id'), name='sys_feedback_event_request'),
        ),
        migrations.AddConstraint(
            model_name='systemfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ['pending', 'processing', 'closed'])), name='sys_feedback_event_from'),
        ),
        migrations.AddConstraint(
            model_name='systemfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['pending', 'processing', 'closed'])), name='sys_feedback_event_to'),
        ),
        migrations.RunPython(create_admin_group, migrations.RunPython.noop),
        migrations.RunPython(migrations.RunPython.noop, prevent_history_loss),
    ]
