# Generated by Django 6.1.1 on 2026-10-09 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prevent_followup_loss(apps, schema_editor):
    events = apps.get_model('changes', 'SystemFeedbackEvent')
    if events.objects.using(schema_editor.connection.alias).filter(kind='followup').exists():
        raise RuntimeError('已有用户追加意见，不能删除其类型标识；请保留沟通历史后再规划回退。')


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0016_review_inbox_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeedbackevent',
            name='kind',
            field=models.CharField(choices=[('manager', '管理员处理'), ('followup', '用户追加')], default='manager', max_length=16),
        ),
        migrations.CreateModel(
            name='SystemFeedbackRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changes.systemfeedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_feedback_read',
                'constraints': [models.UniqueConstraint(fields=('user', 'feedback'), name='feedback_read_user_row')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, prevent_followup_loss),
    ]
