# Fixed definitions from reference workbook, 问题!A3:D29. Instance answers are not defaults.
QUESTIONS = [{'number': 1, 'function': '法规', 'text': '该变更影响设备铭牌或安规标签。', 'remark_hint': None},
 {'number': 2, 'function': '法规', 'text': '该变更影响一个受监管或安规机构关注的关键器件。', 'remark_hint': None},
 {'number': 3, 'function': '法规', 'text': '该变更影响产品注册认证，如国内NMPA，\n受影响的产品是否已获得CE证书。', 'remark_hint': None},
 {'number': 4, 'function': '法规', 'text': '该变更影响WEEE或者RoHS的要求。', 'remark_hint': None},
 {'number': 5,
  'function': '风险',
  'text': '该变更是否引入新的危害(Hazard)或危险情景(Hazardous '
          'Situation)？是否改变了引发危险情景的原因(Causes)，或改变了风险缓和措施(Mitigations)？如果回答“否”，请说明理由。',
  'remark_hint': {'answer': 'N', 'text': '请说明未引入新危害、未改变危险情景原因或风险缓和措施的理由'}},
 {'number': 6, 'function': '研发', 'text': '该变更对现有物料号（包括软件）进行升版，或者该变更创建新的物料号。', 'remark_hint': None},
 {'number': 7, 'function': '研发', 'text': '该变更影响EMC。', 'remark_hint': None},
 {'number': 8, 'function': '研发', 'text': '该变更需要建立新的可销售单元(Commercial Item)，或需要申请新的UDI。', 'remark_hint': None},
 {'number': 9, 'function': '研发', 'text': '该变更影响产品外观。', 'remark_hint': None},
 {'number': 10, 'function': '研发', 'text': '该变更影响产品彩页和产品数据手册中的内容。', 'remark_hint': None},
 {'number': 11, 'function': '研发', 'text': '该变更影响用户手册。', 'remark_hint': None},
 {'number': 12, 'function': '研发', 'text': '该变更影响其他产品。', 'remark_hint': None},
 {'number': 13,
  'function': '研发',
  'text': '该变更是否影响DHF的充分性和适宜性，是否需要设计评审。\n如果不影响DHF的充分性和适宜性，则说明理由',
  'remark_hint': {'answer': 'N', 'text': '请说明 DHF 的充分性和适宜性不受影响的理由'}},
 {'number': 14,
  'function': '研发',
  'text': '该变更是否需要设计验证来保证变更后产品能满足设计输入的要求？\n如果不需要设计验证，请备注理由。',
  'remark_hint': {'answer': 'N', 'text': '请说明不需要设计验证的理由'}},
 {'number': 15, 'function': '研发', 'text': '该变更是否需要设计确认来保证变更后产品能满足用户需求、可用性以及警示标签等的要求？', 'remark_hint': None},
 {'number': 16, 'function': '研发', 'text': '该变更是否影响关键零部件或可追溯零部件？', 'remark_hint': None},
 {'number': 17, 'function': '生产', 'text': '被变更的是否外购零件或属于外购组件的一部分？', 'remark_hint': None},
 {'number': 18,
  'function': '生产',
  'text': '该变更影响内部的生产装配过程、生产测试过程、质量控制计划、进货检验、SOP、生产工具、生产工装、生产仪器设备、操作员培训材料或工时。',
  'remark_hint': None},
 {'number': 19,
  'function': '生产',
  'text': '该变更涉及包装运输或货架期。包括包装、运输、搬运和存储的要求；货架期的变更；标签的更新。',
  'remark_hint': None},
 {'number': 20, 'function': '生产', 'text': '该变更需要暂停发货或让步接收。', 'remark_hint': None},
 {'number': 21, 'function': 'EHS', 'text': '该变更影响EHS。例如提举重量超过20kg、需要新的PPE等。', 'remark_hint': None},
 {'number': 22, 'function': '售后', 'text': '该变更影响维修备件。', 'remark_hint': None},
 {'number': 23, 'function': '售后', 'text': '该变更需要实施现场变更。', 'remark_hint': None},
 {'number': 24, 'function': '售后', 'text': '该变更影响维修手册。', 'remark_hint': None},
 {'number': 25, 'function': '售后', 'text': '该变更需要技术公告(Technical Bulletin)。', 'remark_hint': None},
 {'number': 26, 'function': 'QA', 'text': '注册人制度：该变更影响委托方（注册人）或受托方（受托生产企业）', 'remark_hint': None},
 {'number': 27, 'function': 'QA', 'text': '委托研发：该变更活动是否需要受托研发方或原设计方的参与？', 'remark_hint': None}]
